// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIHs6bUAgEPIwlP-E9z06HbQegT2Xnt4E',
    appId: '1:771491555896:web:48edbe1840c1d2178494cd',
    messagingSenderId: '771491555896',
    projectId: 'neonstrength-a64a7',
    authDomain: 'neonstrength-a64a7.firebaseapp.com',
    storageBucket: 'neonstrength-a64a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfGCVMNZmeF8CDH493NUNI0_0PE8nt1KA',
    appId: '1:771491555896:android:108c1f013ec6e21a8494cd',
    messagingSenderId: '771491555896',
    projectId: 'neonstrength-a64a7',
    storageBucket: 'neonstrength-a64a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUUlO7OhK7kyQaAhSaLsGb6hsLnJeErfg',
    appId: '1:771491555896:ios:140c938321da28a48494cd',
    messagingSenderId: '771491555896',
    projectId: 'neonstrength-a64a7',
    storageBucket: 'neonstrength-a64a7.firebasestorage.app',
    iosBundleId: 'com.example.voltlift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUUlO7OhK7kyQaAhSaLsGb6hsLnJeErfg',
    appId: '1:771491555896:ios:140c938321da28a48494cd',
    messagingSenderId: '771491555896',
    projectId: 'neonstrength-a64a7',
    storageBucket: 'neonstrength-a64a7.firebasestorage.app',
    iosBundleId: 'com.example.voltlift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIHs6bUAgEPIwlP-E9z06HbQegT2Xnt4E',
    appId: '1:771491555896:web:d24bfdd8cdc59c868494cd',
    messagingSenderId: '771491555896',
    projectId: 'neonstrength-a64a7',
    authDomain: 'neonstrength-a64a7.firebaseapp.com',
    storageBucket: 'neonstrength-a64a7.firebasestorage.app',
  );
}
